#version 450

#include "dequant_head.glsl"

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout (binding = 0) readonly buffer A {block_q1_sym32k data_a[];};
layout (binding = 1) writeonly buffer D {D_TYPE data_b[];};

void main() {
    // one thread per sub-block, 32 blocks per workgroup
    const uint ib = gl_WorkGroupID.x * 32 + gl_LocalInvocationID.x / 8;

    if (ib >= p.nel / 256) {
        return;
    }

    const uint s = gl_LocalInvocationID.x % 8;

    const uint scb = uint(data_a[ib].scales[s >> 1]);
    const float dsc = float(data_a[ib].d) * float((s & 1) != 0 ? (scb >> 4) : (scb & 0xF));

    const uint b_idx = 256 * ib + 32 * s;
    const uint q_idx = 4 * s;
    [[unroll]] for (uint j = 0; j < 4; ++j) {
        const uint b = uint(data_a[ib].qs[q_idx + j]);
        [[unroll]] for (uint t = 0; t < 8; ++t) {
            data_b[b_idx + 8 * j + t] = D_TYPE(dsc * (float((b >> t) & 1) - 0.5f));
        }
    }
}
